require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MoocsController do

  let(:user) { FactoryGirl.create(:user) }

  before(:each) do
    login_user user
  end

  # This should return the minimal set of attributes required to create a valid
  # Mooc. As you add validations to Mooc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { name: 'programming languages', platform: 'Coursera'}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MoocsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all moocs as @moocs" do
      mooc = Mooc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:moocs).should eq({ mooc.platform => [mooc] })
    end
  end

  describe "GET new" do
    it "assigns a new mooc as @mooc" do
      get :new, {}, valid_session
      assigns(:mooc).should be_a_new(Mooc)
    end
  end

  describe "GET edit" do
    it "assigns the requested mooc as @mooc" do
      mooc = Mooc.create! valid_attributes
      get :edit, {:id => mooc.to_param}, valid_session
      assigns(:mooc).should eq(mooc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mooc" do
        expect {
          post :create, {:mooc => valid_attributes}, valid_session
        }.to change(Mooc, :count).by(1)
      end

      it "assigns a newly created mooc as @mooc" do
        post :create, {:mooc => valid_attributes}, valid_session
        assigns(:mooc).should be_a(Mooc)
        assigns(:mooc).should be_persisted
      end

      it "redirects to the created mooc" do
        post :create, {:mooc => valid_attributes}, valid_session
        response.should redirect_to(moocs_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mooc as @mooc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mooc.any_instance.stub(:save).and_return(false)
        post :create, {:mooc => {}}, valid_session
        assigns(:mooc).should be_a_new(Mooc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mooc.any_instance.stub(:save).and_return(false)
        post :create, {:mooc => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mooc" do
        mooc = Mooc.create! valid_attributes
        # Assuming there are no other moocs in the database, this
        # specifies that the Mooc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mooc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mooc.to_param, :mooc => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mooc as @mooc" do
        mooc = Mooc.create! valid_attributes
        put :update, {:id => mooc.to_param, :mooc => valid_attributes}, valid_session
        assigns(:mooc).should eq(mooc)
      end

      it "redirects to the mooc" do
        mooc = Mooc.create! valid_attributes
        put :update, {:id => mooc.to_param, :mooc => valid_attributes}, valid_session
        response.should redirect_to(moocs_path)
      end
    end

    describe "with invalid params" do
      it "assigns the mooc as @mooc" do
        mooc = Mooc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mooc.any_instance.stub(:save).and_return(false)
        put :update, {:id => mooc.to_param, :mooc => {}}, valid_session
        assigns(:mooc).should eq(mooc)
      end

      it "re-renders the 'edit' template" do
        mooc = Mooc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mooc.any_instance.stub(:save).and_return(false)
        put :update, {:id => mooc.to_param, :mooc => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mooc" do
      mooc = Mooc.create! valid_attributes
      expect {
        delete :destroy, {:id => mooc.to_param}, valid_session
      }.to change(Mooc, :count).by(-1)
    end

    it "redirects to the moocs list" do
      mooc = Mooc.create! valid_attributes
      delete :destroy, {:id => mooc.to_param}, valid_session
      response.should redirect_to(moocs_path)
    end
  end

end
